### ISSUE TITLE
Restrict command at all

### ISSUE THREAD

**Issue by gilangvperdana** [kaplanelad/shellfirm#111]
### Proposal
Hi Elad, thanks for your good work. Can you add a feature to restrict commands at all? looks like it would be very good if the feature was held. <br>
Very Thanks!

### Use-cases
- Admin set command which is restricted in `/.shellfirm/config.yaml`
- The user cannot execute the command in `/.shellfirm/config.yaml` at all.

### Expected Beahviour
- User can't run command at all if command is on the list of `/.shellfirm/config.yaml`

### Actual Behaviour
- The user can still run the command if the user succeeds in winning the challenge.

**Comment by kaplanelad** [comment]
Hey @gilangvperdana, thanks for giving this idea. 
If I understand correctly, you want to declare on some patterns that the user can't run at all on the machine. 
For example, 
If you don't want to use `git reset --hard`, you want a place in the configuration that says that this patter ID is not allowed to run.
right?

**Comment by gilangvperdana** [comment]
> Hey @gilangvperdana, thanks for giving this idea. If I understand correctly, you want to declare some patterns that the user can't run at all on the machine. For example, If you don't want to use `git reset --hard`, you want a place in the configuration that says that this pattern ID is not allowed to run. Right?

that's right, it would be awesome if given the option without a challenge a.k.a block command completely (as you just caught), I hope this feature will be available soon

your app is awesome, thanks for your great work!

**Comment by kaplanelad** [comment]
Thanks for the feedback, my pleasure.

I'll create a place where you can add the specific pattern id, from the patterns that shellfirm already has, for example [here at line 4](https://github.com/kaplanelad/shellfirm/blob/main/shellfirm/checks/git.yaml#L4).

In case you want to add a custom pattern, you should create the pattern with ID and set it into the config file under  `denied_pattern_ids` field. 

sound good? or do you have a better idea?

**Comment by gilangvperdana** [comment]
> Thanks for the feedback, my pleasure.
> 
> I'll create a place where you can add the specific pattern id, from the patterns that shellfirm already has, for example [here at line 4](https://github.com/kaplanelad/shellfirm/blob/main/shellfirm/checks/git.yaml#L4).
> 
> In case you want to add a custom pattern, you should create the pattern with ID and set it into the config file under `denied_pattern_ids` field.
> 
> sound good? or do you have a better idea?

sounds so good, I can't wait to use it <br>
thank you @kaplanelad for your kindness working on an open source project

**Comment by kaplanelad** [comment]
If you are familiar with rust, you are more then welcome to join me :)

**Comment by kaplanelad** [comment]
@gilangvperdana issue was completed and merge into the main branch.
will update you once bumping new version

Commit: https://github.com/kaplanelad/shellfirm/commit/98c0c3cb700fa454e289084924c93555f52eda63

**Comment by gilangvperdana** [comment]
> If you are familiar with rust, you are more then welcome to join me :)

Thank you for inviting me, but i'm not too familliar with Rust :) <br>

> @gilangvperdana issue was completed and merge into the main branch. will update you once bumping new version
> 
> Commit: [98c0c3c](https://github.com/kaplanelad/shellfirm/commit/98c0c3cb700fa454e289084924c93555f52eda63)

Thanks for your good work, i will try it with spirit

**Comment by gilangvperdana** [comment]
Thanks @kaplanelad your new commit work like a charm
![image](https://user-images.githubusercontent.com/67575515/199022435-6f13017a-9919-4789-a6c2-87fc61231b72.png)

**Comment by kaplanelad** [comment]
Cool, will release a new version soon
