### ISSUE TITLE
Customize deny pattern still can be executed

### ISSUE THREAD

**Issue by gilangvperdana** [kaplanelad/shellfirm#121]
**Shellfirm version**:

**What happened**:
Tried to customize the denied command, but it didn't work.

**What you expected to happen**:
what I think, `shellfirm` can customize commands that can be denied in addition to the default commands like in the shellfirm/checks directory. But it doesn't work well at my place

**How to reproduce it (as minimally and precisely as possible)**:
- I declared the command I want to deny in `.shellfirm/settings.yaml` in the line `deny_patterns_ids` & `includes`
- I did a shellfirm config challenge
- I've seen my pattern customization already entered there
- but after I tried the command, it still works in other words it is not restricted by shellfirm. Unlike the default commands that `shellfirm` give such as `git reset` etc.

**Anything else we need to know?**:
- we all know that this app has big vision and i already feel it
- I am very happy that you build an application like this, it is very useful in my opinion
- Thanks @kaplanelad 

**OS**:
- Ubuntu 20.04LTS Server

**Evidence**
![image](https://user-images.githubusercontent.com/67575515/199307060-3d6d0ee4-e6c6-4803-b75b-df3a1245b0af.png)
- `git reset` command rejected as usual.
- `openstack` command not rejected as usual.

**Comment by kaplanelad** [comment]
Hey @gilangvperdana, 
Do you want to create a custom pattern to catch?

About your modifications: 
i'm not recommended to modify the setting manually. 
to add a pattern to deny list, tap the command `shellfirm config deny`
See example:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/1224389/199332127-0826d58c-fc94-458d-8d13-373d95dd7e52.png">

**Comment by gilangvperdana** [comment]
> Hey @gilangvperdana, i'm not recommended to modify the setting manually. to add a pattern to deny list, tap the command `shellfirm config deny` See example: <img alt="image" width="619" src="https://user-images.githubusercontent.com/1224389/199332127-0826d58c-fc94-458d-8d13-373d95dd7e52.png">

Thanks @kaplanelad it's working fine
