### ISSUE TITLE
Custom checks

### ISSUE THREAD

**Issue by JakobEdding** [kaplanelad/shellfirm#125]
Is it still possible to configure custom checks? I remember it used to be possible by setting `checks` to an array of checks in settings.yaml (at the time config.yaml).

**Comment by ManupaDogflau** [comment]
Im also curious

**Comment by kaplanelad** [comment]
I'll check the option to bring it back. 

Just out of curiosity what is missing to you?

**Comment by adamallegro** [comment]
At every project I use to work I have different commands that can set the (project) world on fire! Example: calling web service by `curl` can be dangerous. Running specific `make` tasks can be dangerous also. It would be great to add custom list of commands!
