### ISSUE TITLE
Add Remove Directory to list of Risky Commands

### ISSUE THREAD

**Issue by Geoff12889** [kaplanelad/shellfirm#128]
Can we have the option to enable rmdir from the list of risky commands?

**Comment by kaplanelad** [comment]
Hey @Geoff12889, thanks for that idea.
Do you want to try adding this command pattern [here](https://github.com/kaplanelad/shellfirm/blob/main/shellfirm/checks/fs-strict.yaml) and open a pull request?

**Comment by Geoff12889** [comment]
Wow, appreciate the quick response! Yeah, will give it a shot. Thanks

**Comment by Geoff12889** [comment]
Sorry for the silly question, but how do I build after I make those changes? I tried the Makefile but it says:
`make: Nothing to be done for `Makefile'.`

**Comment by Geoff12889** [comment]
The test failed, and I'm stuck on what to try next:

`running 2 tests
test test_missing_patterns_coverage ... ok
stored new snapshot /Users/[username]/Downloads/shellfirm-main/shellfirm/tests/snapshots/checks__fs-strict-folder_deletion.yaml.snap.new
test test_checks ... FAILED

failures:

---- test_checks stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Differences ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: shellfirm/tests/snapshots/checks__fs-strict-folder_deletion.yaml.snap
Snapshot: fs-strict-folder_deletion.yaml
Source: shellfirm/tests/checks.rs:52
────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: test_file_results
────────────────────────────────────────────────────────────────────────────────────────────────────
+new results
────────────┬───────────────────────────────────────────────────────────────────────────────────────
          0 │+[
          1 │+    TestSensitivePatternsResult {
          2 │+        file_path: "fs-strict-folder_deletion.yaml",
          3 │+        test: "rmdir TestFolder",
          4 │+        check_detection_ids: [],
          5 │+        test_description: "match command by finding existing file",
          6 │+    },
          7 │+    TestSensitivePatternsResult {
          8 │+        file_path: "fs-strict-folder_deletion.yaml",
          9 │+        test: "rmdir -pv TestFolder",
         10 │+        check_detection_ids: [],
         11 │+        test_description: "match command with flags",
         12 │+    },
         13 │+    TestSensitivePatternsResult {
         14 │+        file_path: "fs-strict-folder_deletion.yaml",
         15 │+        test: "rmdir    -pv    TestFolder",
         16 │+        check_detection_ids: [],
         17 │+        test_description: "match command with spaces",
         18 │+    },
         19 │+]
────────────┴───────────────────────────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'test_checks' panicked at 'snapshot assertion for 'fs-strict-folder_deletion.yaml' failed in line 52', /Users/[username]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.20.0/src/runtime.rs:516:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_checks

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.11s

error: test failed, to rerun pass `--test checks``

**Comment by Geoff12889** [comment]
[#129](https://github.com/kaplanelad/shellfirm/pull/129)

**Comment by kaplanelad** [comment]
Thanks @Geoff12889 for your PR.
I'll release a new version later on today
