### ISSUE TITLE
rm -R is not getting checked

### ISSUE THREAD

**Issue by ManupaDogflau** [kaplanelad/shellfirm#131]
**Shellfirm version**:

**What happened**: Anything

**What you expected to happen**: Check the command because it is equivalent to "rm -r ."

**How to reproduce it (as minimally and precisely as possible)**: run "rm - R ." or
"RUST_LOG=trace shellfirm pre-command --command "rm -R .""

It gives no more traces

**Anything else we need to know?**: No, but you are doing a great job

**OS**: Ubuntu 22.04

**Comment by kaplanelad** [comment]
Thank you, @ManupaDogflau, for bringing this issue to my attention. Would you like  opening a pull request, or would you prefer if I handle it?

**Comment by kaplanelad** [comment]
@ManupaDogflau i  released  in version 0.2.9.

To verify the installed version, use the following command: `shellfirm --version`.

**Note**: Please ensure that you test it in a temporary folder, and exercise caution to avoid accidentally deleting a necessary real folder.

See the following example
![image](https://github.com/kaplanelad/shellfirm/assets/1224389/de72c07b-ab84-418e-a0c0-d860a49272a3)

**Comment by ManupaDogflau** [comment]
Sry for not been able to respond to this quickier. It works perfectly

Thank you very much, this can be closed when you want
