### ISSUE TITLE
Fish shell support

### ISSUE THREAD

**Issue by mhausenblas** [kaplanelad/shellfirm#59]
### Proposal

Support `shellfirm` in [fish](https://fishshell.com/).

### Use-cases

I'm using `fish` as my default shell and failed to make it work so assuming it's not yet supported there?

**Comment by kaplanelad** [comment]
Hey @mhausenblas, 
 I'm not familiar with fisshell and how the plugins work there.  let me investigate, and I'll keep you updated

Thanks for opening this issue.

**Comment by kaplanelad** [comment]
@mhausenblas, which plugin manager are you working with? 
Fisher or Fundle?

**Comment by mhausenblas** [comment]
Thank you @kaplanelad, appreciate the swift response and your willingness to look into it! 

> which plugin manager are you working with?

I don't use a plugin manager (yet) but I do have my setup publicly documented via https://o11y.engineering/my-taf-setup-faa6bd0f1076 if that helps?

**Comment by theRookieCoder** [comment]
Hey I'm also interested in fish support as I use fish too. I've checked the repositories and fisher seems to be the more mature and active one. I haven't actually ever used fish plugins before either but I think fisher would be better to develop for

**Comment by kaplanelad** [comment]
Hey @mhausenblas and @theRookieCoder,

I working on a solution and opened an issue in fishshell repository: https://github.com/fish-shell/fish-shell/issues/8634 to try getting their help also. 

Please go to [my issue](https://github.com/fish-shell/fish-shell/issues/8634) add a comment that you looking for this solution as well maybe it will help to promote their answer.

**Comment by kaplanelad** [comment]
Hey, 
I have created a fish config file that integrates shellfirm with fishshell. #61 

please do the following steps:
1. Download shellfirm via brew or release page: https://github.com/kaplanelad/shellfirm/blob/main/docs/installation/fishshell.md
2. Read fishshell doc: https://github.com/kaplanelad/shellfirm/blob/main/docs/installation/fishshell.md
3. Verify installation: https://github.com/kaplanelad/shellfirm#verify-installation

There is a visualization bug that will handle in the next release. [new issue created](https://github.com/kaplanelad/shellfirm/issues/62)

Please let me know if it works properly for closing this issue

**Comment by mhausenblas** [comment]
Thanks a lot @kaplanelad! I just tried it out (installed the config) but I don't seem to get it working. I'm using                                                                                                                                                                                                                                                                                                 `fish` in version 3.3.1. Not sure what I am missing.

**Comment by mhausenblas** [comment]
OK, my bad. Now it works :)

Two notes: 

1. it doesn't apply to the current Fish session, need to launch a new one.
2. A single CTRL+C doesn't seem to work to cancel:

![image](https://user-images.githubusercontent.com/52594/149510362-a10079e3-e589-4738-99f9-3b2934d22427.png)

**Comment by mhausenblas** [comment]
> Please let me know if it works properly for closing this issue

To summarise: from my point of view we can close this issue. If you can reproduce the double-CTRL+C issue I think a new issue to track that akin to #62  would make sense.

Again, thank you so much for your work, really appreciate it!

**Comment by theRookieCoder** [comment]
Hey elad the Fish implementation works! Thank you so much for doing this so quickly I'd just like to congratulate you for your dedication. I had the same issues michael had but since these have been moved to the other issues (#62) I think we can close this

**Comment by kaplanelad** [comment]
your welcome!
