### ISSUE TITLE
Make `$XDG_CONFIG_HOME/shellfirm/` the default config path

### ISSUE THREAD

**Issue by roadkell** [kaplanelad/shellfirm#67]
### Proposal
Make `$XDG_CONFIG_HOME/shellfirm/` the default path for all configuration, in accordance with [XDG dir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and to prevent clutter of `$HOME` dir.

Alternatively, allow user to set the path explicitly (with an env variable, for example).

Also, thank you for the project!

**Comment by kaplanelad** [comment]
Hey @roadkell, let me do a little research on $XDG_CONFIG_HOME, and I'll get back to you.
And thanks for your feedback

**Comment by gaoDean** [comment]
+1

**Comment by kaplanelad** [comment]
thanks @gaoDean i'll work on it this week.
@roadkell & @gaoDean, 
Just to make sure I'm doing the change in the change in the right place. 
Your want me to search if env var `$XDG_CONFIG_HOME` exists. 
If yes, take that path from `$XDG_CONFIG_HOME`; else, take it from $HOME. 
Right?

**Comment by gaoDean** [comment]
yeah, I'm pretty sure that's correct, thanks so much!

**Comment by kaplanelad** [comment]
@roadkell & @gaoDean,
Can you please share with me the error you are getting when you run shellfirm? or you just want to save the state in somewhere elase.

I need to add a backward compatibility to old version and want to make sure that I'm not brake something in the next releae

**Comment by gaoDean** [comment]
We don't get an error, at least I don't, we just want our home directories to be clean so we move everything into $XDG_CONFIG_HOME. Perhaps you could just check for the directories, first check for ~/.shellfirm, then $XDG_CONFIG_HOME/shellfirm, whichever exists, go with that config.

**Comment by kaplanelad** [comment]
Hey @roadkell @gaoDean, 
New version was released `0.2.3` with $XDG_CONFIG_HOME support. 
Before closing this issue can you please confirm tha change?

**Comment by gaoDean** [comment]
@kaplanelad hey, I can not confirm that it is working because every time I run "shellfirm" it creates a new ~/.shellfirm directory in the home directory, even though there is already one in ~/.config/shellfirm. Thanks

**Comment by gaoDean** [comment]
apparently it automatically creates the ~/.shellfirm directory immediently after I've deleted it?

**Comment by gaoDean** [comment]
also, with ~/.shellfirm in home, the $XDG_CONFIG_HOME/shellfirm isn't sourced, though I realise now that it is the desired effect.

**Comment by kaplanelad** [comment]
you need to do the following steps:
1. Update shellfirm to `0.2.3` version. run shellfirm --version to validate it
2. Open a new terminal tab
3. Selete .shellfirm from home directory
4. Run any command in your terminal (just for execute shellfirm)
5. Check .shellfirm directory

**Comment by gaoDean** [comment]
huh, i have the directory structure in my usr local cellar:
```
shellfirm
└── 0.2.3
    ├── INSTALL_RECEIPT.json
    └── bin
        └── shellfirm
```
and when I run `./usr/local/Cellar/shellfirm/0.2.3/bin/shellfirm --version`, it gives me 0.2.2.

**Comment by gaoDean** [comment]
sorry, but is there anywhere that defines the version of shellfirm?

**Comment by kaplanelad** [comment]
It looks i had a problem with the bumping version. releasing a new one

**Comment by gaoDean** [comment]
alright thanks

**Comment by kaplanelad** [comment]
you can update now to the lates (0.2.4)

after update yo can do the following steps that I wrote above.
you can also run `shellfirm --log debug`. search log with the prefix: `configuration folder found ...`
you can see where shellfim point. if it is still not the config path, delete the folder that you saw in the log and run shellfirm again

**Comment by gaoDean** [comment]
hey, for some reason the script keeps creating shellfirm config at `/Users/deangao/Library/Application Support/shellfirm`. 
`XDG_CONFIG_HOME` is set to `/Users/deangao/.config`

**Comment by gaoDean** [comment]
I deleted the shellfirm application support dir but it reappears

**Comment by roadkell** [comment]
> search if env var `$XDG_CONFIG_HOME` exists. If yes, take that path from `$XDG_CONFIG_HOME`; else, take it from $HOME. Right?

From the spec: "If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used"

**Comment by kaplanelad** [comment]
Yes @roadkell you right. 
Can ii close this issue?

**Comment by kaplanelad** [comment]
@gaoDean this is the change as @roadkell wrote here,  
1. if .shellfirm folder is exists int the from the previous  version, the folder keep and shellfirm works with that folder
2. if the folder does not exists
   - checks if the `$XDG_CONFIG_HOME` is set 
   - default his path: `Some($HOME/.config)`

You can see the PR here: https://github.com/kaplanelad/shellfirm/pull/87/files

**Comment by gaoDean** [comment]
@kaplanelad `shellfirm --log DEBUG` says that I have config folder at `~/Library/Application\ Support/shellfirm`. When I delete that folder, shellfirm works properly, and the folder doesn't reappear. When I run `shellfirm --log DEBUG again`, it creates the folder at `~/Library/Application\ Support/shellfirm` again.

**Comment by kaplanelad** [comment]
The flow that you describe here here is ok.
What is the problem?

**Comment by roadkell** [comment]
It works for me as expected, thank you. The issue can be closed, I think.
