### ISSUE TITLE
Zsh installation instructions without Oh My Zsh

### ISSUE THREAD

**Issue by igorkulman** [kaplanelad/shellfirm#78]
### Proposal

Please add installation instructions for Zsh without using  Oh My Zsh

### Use-cases

People using Zsh without  Oh My Zsh

### Attempted Solutions

Pasting `shellfirm.plugin.zsh` to `.zshrc`

**Comment by kaplanelad** [comment]
Hey @igorkulman, thanks for this issue! 
Can you elaborate a bit how you manage your plugins in  Zsh?

**Comment by igorkulman** [comment]
Just `source x.zsh`, all the "plugins" allow for such installation, here is an example https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md#manual-git-clone

**Comment by gaoDean** [comment]
+1, personally this is what I use:
`[ -f $HOME/repos/oth/shellfirm/shell-plugins/shellfirm.plugin.zsh ] && source $HOME/repos/oth/shellfirm/shell-plugins/shellfirm.plugin.zsh
`

**Comment by kaplanelad** [comment]
Hey @igorkulman
I'll upload a detailed doc + docker image later this week, but it the meantime you load `shellfirm` adding the following commands in your `~/.zshrc` file
```sh
exec-shellfirm () {
  if [[ "${BUFFER}" == *"shellfirm pre-command"* ]]; then
        return
    fi
    shellfirm pre-command --command "${BUFFER}"
  zle .accept-line
}
zle -N accept-line exec-shellfirm
```

let me know if it helped

**Comment by kaplanelad** [comment]
Hey @igorkulman, 
I have added instructor here: https://github.com/kaplanelad/shellfirm#select-your-shell

Also, prepare a docker image 
https://github.com/kaplanelad/shellfirm/tree/main/docs/docker/zsh

**Comment by igorkulman** [comment]
Thanks
