### ISSUE TITLE
Add check for crontab -r

### ISSUE THREAD

**Issue by warrenski** [kaplanelad/shellfirm#80]
Please add a check for:

`crontab -r`

The above command is risky because it'll remove the user's entire crontab of scheduled tasks. Since users typically would want to edit their crontab using the `-e` option, an accidental keypress of neighbouring `-r` would be disastrous. Yes, an alias to include the `-i` (interactive) option could be set to at least first prompt the user before its removal, but users typically only learn about this option once the damage is already done.

**Comment by kaplanelad** [comment]
Thanks @warrenski for your suggestion. definitely risky command :) 
Do you want to open a PR you can add this pattern to [base.yaml](https://github.com/kaplanelad/shellfirm/blob/main/shellfirm/checks/base.yaml).

**Comment by warrenski** [comment]
My regex pattern is a bit naive, for example it wouldn't catch something like `crontab -u bob -r`, but it's a starting point for someone else to improve upon.

**Comment by warrenski** [comment]
Thanks for resolving this request. Closing issue.

**Comment by kaplanelad** [comment]
I'll update you when new version release.
Thanks for continuing!
