### ISSUE TITLE
Terraform

### ISSUE THREAD

**Issue by kaplanelad** [kaplanelad/shellfirm#90]
List of possible risky patterns:

* `terraform apply` - with flag [-auto-approve](https://www.terraform.io/cli/commands/apply#auto-approve)
* `terraform force-unlock` - with flag [-force](https://www.terraform.io/cli/commands/force-unlock#force)
* `terraform state mv` - without dryrun flag https://www.terraform.io/cli/commands/state/mv
* `terraform state replace-provider` - with [-auto-approve](https://www.terraform.io/cli/commands/state/replace-provider#auto-approve)
* `terraform state rm` - without [-dry-run](https://www.terraform.io/cli/commands/state/rm#dry-run)
* `terraform workspace delete` - with [-force](https://www.terraform.io/cli/commands/workspace/delete#force)

**Comment by inFocus7** [comment]
If this hasn't been picked up yet, could I be assigned to it? 👀

**Comment by kaplanelad** [comment]
sure, go ahead thanks you.
Let me know if you needs my assist.

**Comment by kaplanelad** [comment]
Hey @inFocus7 I summarize the risky patterns in Terraform and replace the issue description. 
WDYT?

**Comment by inFocus7** [comment]
That sounds good! 
I'm working on a new branch off of the main repo right now. Is that fine? Or should I create a fork?

**Comment by kaplanelad** [comment]
You need to fork this repo(until you become a core committer  😀 )

don't forget to add the documentation in two places:
1. https://github.com/kaplanelad/shellfirm#risky-commands
2. https://github.com/kaplanelad/shellfirm/tree/main/docs/checks

**Comment by kaplanelad** [comment]
Hey @inFocus7,
Do you want to give me an example of your regex problem? i can help you to finish this PR
regex example: ____
prompt command: ____
ignore prompt command: ____
